import { ConversationSummary, MessagesByConversation } from "@/types/messaging";

export const MOCK_CONVERSATIONS: ConversationSummary[] = [
  {
    id: "1",
    title: "Melbourne Education Hub",
    subtitle: "Lukas Abraham · HR Manager",
    lastMessagePreview:
      "Thanks for your interest! We would love to discuss the volunteer opportunity with you.",
    lastActivityAt: new Date().toISOString(),
    hasUnread: true,
    unreadCount: 1,
    isArchived: false,
    opportunityId: "employment-demo",
  },
  {
    id: "2",
    title: "Green Energy Corp",
    subtitle: "MTSI",
    lastMessagePreview:
      "Thanks for the advice about the project – it was really helpful.",
    lastActivityAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    hasUnread: true,
    unreadCount: 3,
    isArchived: false,
    opportunityId: null,
  },
  {
    id: "3",
    title: "UniConnected Platform",
    subtitle: "UniConnected",
    lastMessagePreview: "Looking forward to hearing your thoughts on this.",
    lastActivityAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    hasUnread: false,
    unreadCount: 0,
    isArchived: false,
    opportunityId: null,
  },
  {
    id: "4",
    title: "Employment Demo",
    subtitle: "Coordinator",
    lastMessagePreview: "We’ll get back to you with next steps shortly.",
    lastActivityAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    hasUnread: false,
    unreadCount: 0,
    isArchived: true,
    opportunityId: "employment-demo",
  },
  {
    id: "5",
    title: "Melbourne Education Hub",
    subtitle: "Lukas Abraham · HR Manager",
    lastMessagePreview:
      "Thanks for your interest! We would love to discuss the volunteer opportunity with you.",
    lastActivityAt: new Date().toISOString(),
    hasUnread: true,
    unreadCount: 1,
    isArchived: false,
    opportunityId: "employment-demo",
  },
  {
    id: "6",
    title: "Green Energy Corp",
    subtitle: "MTSI",
    lastMessagePreview:
      "Thanks for the advice about the project – it was really helpful.",
    lastActivityAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    hasUnread: true,
    unreadCount: 3,
    isArchived: false,
    opportunityId: null,
  },
  {
    id: "7",
    title: "UniConnected Platform",
    subtitle: "UniConnected",
    lastMessagePreview: "Looking forward to hearing your thoughts on this.",
    lastActivityAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    hasUnread: false,
    unreadCount: 0,
    isArchived: false,
    opportunityId: null,
  },
  {
    id: "8",
    title: "Employment Demo",
    subtitle: "Coordinator",
    lastMessagePreview: "We’ll get back to you with next steps shortly.",
    lastActivityAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    hasUnread: false,
    unreadCount: 0,
    isArchived: true,
    opportunityId: "employment-demo",
  },
  {
    id: "9",
    title: "Melbourne Education Hub",
    subtitle: "Lukas Abraham · HR Manager",
    lastMessagePreview:
      "Thanks for your interest! We would love to discuss the volunteer opportunity with you.",
    lastActivityAt: new Date().toISOString(),
    hasUnread: true,
    unreadCount: 1,
    isArchived: false,
    opportunityId: "employment-demo",
  },
  {
    id: "10",
    title: "Green Energy Corp",
    subtitle: "MTSI",
    lastMessagePreview:
      "Thanks for the advice about the project – it was really helpful.",
    lastActivityAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    hasUnread: true,
    unreadCount: 3,
    isArchived: false,
    opportunityId: null,
  },
  {
    id: "11",
    title: "UniConnected Platform",
    subtitle: "UniConnected",
    lastMessagePreview: "Looking forward to hearing your thoughts on this.",
    lastActivityAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    hasUnread: false,
    unreadCount: 0,
    isArchived: false,
    opportunityId: null,
  },
  {
    id: "12",
    title: "Employment Demo",
    subtitle: "Coordinator",
    lastMessagePreview: "We’ll get back to you with next steps shortly.",
    lastActivityAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    hasUnread: false,
    unreadCount: 0,
    isArchived: true,
    opportunityId: "employment-demo",
  },
  {
    id: "13",
    title: "Melbourne Education Hub",
    subtitle: "Lukas Abraham · HR Manager",
    lastMessagePreview:
      "Thanks for your interest! We would love to discuss the volunteer opportunity with you.",
    lastActivityAt: new Date().toISOString(),
    hasUnread: true,
    unreadCount: 1,
    isArchived: false,
    opportunityId: "employment-demo",
  },
  {
    id: "14",
    title: "Green Energy Corp",
    subtitle: "MTSI",
    lastMessagePreview:
      "Thanks for the advice about the project – it was really helpful.",
    lastActivityAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    hasUnread: true,
    unreadCount: 3,
    isArchived: false,
    opportunityId: null,
  },
  {
    id: "15",
    title: "UniConnected Platform",
    subtitle: "UniConnected",
    lastMessagePreview: "Looking forward to hearing your thoughts on this.",
    lastActivityAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    hasUnread: false,
    unreadCount: 0,
    isArchived: false,
    opportunityId: null,
  },
  {
    id: "16",
    title: "Employment Demo",
    subtitle: "Coordinator",
    lastMessagePreview: "We’ll get back to you with next steps shortly.",
    lastActivityAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    hasUnread: false,
    unreadCount: 0,
    isArchived: true,
    opportunityId: "employment-demo",
  },
];

export const MOCK_MESSAGES: MessagesByConversation = {
  "1": [
    {
      id: "m1",
      conversationId: "1",
      sender: "me",
      text: "Thanks for your interest! We would love to discuss the volunteer opportunity with you.",
      createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "m2",
      conversationId: "1",
      sender: "them",
      text: "Thanks for your interest! We would love to discuss the volunteer opportunity with you.",
      createdAt: new Date(Date.now() - 2.5 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "m1",
      conversationId: "1",
      sender: "me",
      text: "Thanks for your interest! We would love to discuss the volunteer opportunity with you.",
      createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "m2",
      conversationId: "1",
      sender: "them",
      text: "Thanks for your interest! We would love to discuss the volunteer opportunity with you.",
      createdAt: new Date(Date.now() - 2.5 * 60 * 60 * 1000).toISOString(),
    },
  ],
  "2": [
    {
      id: "m3",
      conversationId: "2",
      sender: "them",
      text: "Thanks for the advice about the project – it was really helpful.",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "m4",
      conversationId: "2",
      sender: "them",
      text: "Thanks for the advice about the project – it was really helpful.",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "m5",
      conversationId: "2",
      sender: "them",
      text: "Thanks for the advice about the project – it was really helpful.",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "m6",
      conversationId: "2",
      sender: "them",
      text: "Thanks for the advice about the project – it was really helpful.",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "m7",
      conversationId: "2",
      sender: "them",
      text: "Thanks for the advice about the project – it was really helpful.",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
  ],
  "3": [
    {
      id: "m8",
      conversationId: "3",
      sender: "them",
      text: "Thanks for the advice about the project – it was really helpful.",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "m9",
      conversationId: "3",
      sender: "them",
      text: "Thanks for the advice about the project – it was really helpful.",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "m11",
      conversationId: "3",
      sender: "them",
      text: "Thanks for the advice about the project – it was really helpful.",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "m10",
      conversationId: "3",
      sender: "them",
      text: "Thanks for the advice about the project – it was really helpful.",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "m12",
      conversationId: "3",
      sender: "them",
      text: "Thanks for the advice about the project – it was really helpful.",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
  ],
  "4": [
    {
      id: "m13",
      conversationId: "4",
      sender: "them",
      text: "Thanks for the advice about the project – it was really helpful.",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "m14",
      conversationId: "4",
      sender: "them",
      text: "Thanks for the advice about the project – it was really helpful.",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "m15",
      conversationId: "4",
      sender: "them",
      text: "Thanks for the advice about the project – it was really helpful.",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
  ],
  "5": [
    {
      id: "m16",
      conversationId: "5",
      sender: "them",
      text: "Thanks for the advice about the project – it was really helpful.",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "m17",
      conversationId: "5",
      sender: "them",
      text: "Thanks for the advice about the project – it was really helpful.",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
  ],
  "6": [
    {
      id: "m18",
      conversationId: "6",
      sender: "them",
      text: "Thanks for the advice about the project – it was really helpful.",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
  ],
  "7": [
    {
      id: "m19",
      conversationId: "7",
      sender: "them",
      text: "Thanks for the advice about the project – it was really helpful.",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "m20",
      conversationId: "7",
      sender: "them",
      text: "Thanks for the advice about the project – it was really helpful.",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "m21",
      conversationId: "7",
      sender: "them",
      text: "Thanks for the advice about the project – it was really helpful.",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
  ],
  "8": [
    {
      id: "m22",
      conversationId: "8",
      sender: "them",
      text: "Thanks for the advice about the project – it was really helpful.",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "m23",
      conversationId: "8",
      sender: "them",
      text: "Thanks for the advice about the project – it was really helpful.",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "m24",
      conversationId: "8",
      sender: "them",
      text: "Thanks for the advice about the project – it was really helpful.",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
  ],
  "9": [
    {
      id: "m25",
      conversationId: "9",
      sender: "them",
      text: "Thanks for the advice about the project – it was really helpful.",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "m26",
      conversationId: "9",
      sender: "them",
      text: "Thanks for the advice about the project – it was really helpful.",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "m27",
      conversationId: "9",
      sender: "them",
      text: "Thanks for the advice about the project – it was really helpful.",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
  ],
  "10": [
    {
      id: "m28",
      conversationId: "10",
      sender: "them",
      text: "Thanks for the advice about the project – it was really helpful.",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "m29",
      conversationId: "10",
      sender: "them",
      text: "Thanks for the advice about the project – it was really helpful.",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "m30",
      conversationId: "10",
      sender: "them",
      text: "Thanks for the advice about the project – it was really helpful.",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
  ],
  "11": [
    {
      id: "m31",
      conversationId: "11",
      sender: "them",
      text: "Thanks for the advice about the project – it was really helpful.",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
  ],
  "12": [
    {
      id: "m32",
      conversationId: "12",
      sender: "them",
      text: "Thanks for the advice about the project – it was really helpful.",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "m33",
      conversationId: "12",
      sender: "them",
      text: "Thanks for the advice about the project – it was really helpful.",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "m34",
      conversationId: "12",
      sender: "them",
      text: "Thanks for the advice about the project – it was really helpful.",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
  ],
  "13": [
    {
      id: "m35",
      conversationId: "13",
      sender: "them",
      text: "Thanks for the advice about the project – it was really helpful.",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "m36",
      conversationId: "13",
      sender: "them",
      text: "Thanks for the advice about the project – it was really helpful.",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "m37",
      conversationId: "13",
      sender: "them",
      text: "Thanks for the advice about the project – it was really helpful.",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
  ],
  "14": [
    {
      id: "m38",
      conversationId: "14",
      sender: "them",
      text: "Thanks for the advice about the project – it was really helpful.",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "m39",
      conversationId: "14",
      sender: "them",
      text: "Thanks for the advice about the project – it was really helpful.",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "m40",
      conversationId: "14",
      sender: "them",
      text: "Thanks for the advice about the project – it was really helpful.",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
  ],
  "15": [
    {
      id: "m41",
      conversationId: "15",
      sender: "them",
      text: "Thanks for the advice about the project – it was really helpful.",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
  ],
};
