import { ConversationSummary, MessagesByConversation } from "@/types/messaging";

export const MOCK_CONVERSATIONS: ConversationSummary[] = [
  {
    id: "1",
    title: "Melbourne Education Hub",
    subtitle: "Lukas Abraham · HR Manager",
    lastMessagePreview:
      "Thanks for your interest! We would love to discuss the volunteer opportunity with you.",
    lastActivityAt: new Date().toISOString(),
    hasUnread: true,
    unreadCount: 1,
    isArchived: false,
    opportunityId: "employment-demo",
  },
  {
    id: "2",
    title: "Green Energy Corp",
    subtitle: "MTSI",
    lastMessagePreview:
      "Thanks for the advice about the project – it was really helpful.",
    lastActivityAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    hasUnread: true,
    unreadCount: 3,
    isArchived: false,
    opportunityId: null,
  },
  {
    id: "3",
    title: "UniConnected Platform",
    subtitle: "UniConnected",
    lastMessagePreview: "Looking forward to hearing your thoughts on this.",
    lastActivityAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    hasUnread: false,
    unreadCount: 0,
    isArchived: false,
    opportunityId: null,
  },
  {
    id: "4",
    title: "Employment Demo",
    subtitle: "Coordinator",
    lastMessagePreview: "We’ll get back to you with next steps shortly.",
    lastActivityAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    hasUnread: false,
    unreadCount: 0,
    isArchived: true,
    opportunityId: "employment-demo",
  },
  {
    id: "5",
    title: "Melbourne Education Hub",
    subtitle: "Lukas Abraham · HR Manager",
    lastMessagePreview:
      "Thanks for your interest! We would love to discuss the volunteer opportunity with you.",
    lastActivityAt: new Date().toISOString(),
    hasUnread: true,
    unreadCount: 1,
    isArchived: false,
    opportunityId: "employment-demo",
  },
  {
    id: "6",
    title: "Green Energy Corp",
    subtitle: "MTSI",
    lastMessagePreview:
      "Thanks for the advice about the project – it was really helpful.",
    lastActivityAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    hasUnread: true,
    unreadCount: 3,
    isArchived: false,
    opportunityId: null,
  },
  {
    id: "7",
    title: "UniConnected Platform",
    subtitle: "UniConnected",
    lastMessagePreview: "Looking forward to hearing your thoughts on this.",
    lastActivityAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    hasUnread: false,
    unreadCount: 0,
    isArchived: false,
    opportunityId: null,
  },
  {
    id: "8",
    title: "Employment Demo",
    subtitle: "Coordinator",
    lastMessagePreview: "We’ll get back to you with next steps shortly.",
    lastActivityAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    hasUnread: false,
    unreadCount: 0,
    isArchived: true,
    opportunityId: "employment-demo",
  },
  {
    id: "9",
    title: "Melbourne Education Hub",
    subtitle: "Lukas Abraham · HR Manager",
    lastMessagePreview:
      "Thanks for your interest! We would love to discuss the volunteer opportunity with you.",
    lastActivityAt: new Date().toISOString(),
    hasUnread: true,
    unreadCount: 1,
    isArchived: false,
    opportunityId: "employment-demo",
  },
  {
    id: "10",
    title: "Green Energy Corp",
    subtitle: "MTSI",
    lastMessagePreview:
      "Thanks for the advice about the project – it was really helpful.",
    lastActivityAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    hasUnread: true,
    unreadCount: 3,
    isArchived: false,
    opportunityId: null,
  },
  {
    id: "11",
    title: "UniConnected Platform",
    subtitle: "UniConnected",
    lastMessagePreview: "Looking forward to hearing your thoughts on this.",
    lastActivityAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    hasUnread: false,
    unreadCount: 0,
    isArchived: false,
    opportunityId: null,
  },
  {
    id: "12",
    title: "Employment Demo",
    subtitle: "Coordinator",
    lastMessagePreview: "We’ll get back to you with next steps shortly.",
    lastActivityAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    hasUnread: false,
    unreadCount: 0,
    isArchived: true,
    opportunityId: "employment-demo",
  },
  {
    id: "13",
    title: "Melbourne Education Hub",
    subtitle: "Lukas Abraham · HR Manager",
    lastMessagePreview:
      "Thanks for your interest! We would love to discuss the volunteer opportunity with you.",
    lastActivityAt: new Date().toISOString(),
    hasUnread: true,
    unreadCount: 1,
    isArchived: false,
    opportunityId: "employment-demo",
  },
  {
    id: "14",
    title: "Green Energy Corp",
    subtitle: "MTSI",
    lastMessagePreview:
      "Thanks for the advice about the project – it was really helpful.",
    lastActivityAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    hasUnread: true,
    unreadCount: 3,
    isArchived: false,
    opportunityId: null,
  },
  {
    id: "15",
    title: "UniConnected Platform",
    subtitle: "UniConnected",
    lastMessagePreview: "Looking forward to hearing your thoughts on this.",
    lastActivityAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    hasUnread: false,
    unreadCount: 0,
    isArchived: false,
    opportunityId: null,
  },
  {
    id: "16",
    title: "Employment Demo",
    subtitle: "Coordinator",
    lastMessagePreview: "We’ll get back to you with next steps shortly.",
    lastActivityAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    hasUnread: false,
    unreadCount: 0,
    isArchived: true,
    opportunityId: "employment-demo",
  },
];

export const MOCK_MESSAGES: MessagesByConversation = {
  "1": [
    {
      id: "m1",
      conversationId: "1",
      sender: "me",
      text: "Thanks for your interest! We would love to discuss the volunteer opportunity with you.",
      createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "m2",
      conversationId: "1",
      sender: "them",
      text: "Thanks for your interest! We would love to discuss the volunteer opportunity with you.",
      createdAt: new Date(Date.now() - 2.5 * 60 * 60 * 1000).toISOString(),
    },
  ],
  "2": [
    {
      id: "m3",
      conversationId: "2",
      sender: "them",
      text: "Thanks for the advice about the project – it was really helpful.",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
  ],
  "3": [],
  "4": [],
};
