import IconArrowRight from "./IconArrowRight";
import IconArrowLeft from "./IconArrowLeft";
import IconAvatar from "./IconAvatar";
import IconFilter from "./IconFilter";
import IconMoreEllipsis from "./IconMoreEllipsis";
import IconFolder from "./IconFolder";
import IconPlus from "./IconPlus";
import IconFolderSingleTrace from "./IconFolderSingleTrace";
import IconHome from "./IconHome";
import IconMessage from "./IconMessage";
import IconSupport from "./IconSupport";
import IconUser from "./IconUser";
import IconOpportunity from "./IconOpportunity";
import IconCheck from "./IconCheck";
export { IconArrowRight, IconArrowLeft, IconAvatar, IconFilter, IconMoreEllipsis, IconFolder, IconPlus, IconFolderSingleTrace, IconHome, IconMessage, IconSupport, IconUser, IconOpportunity, IconCheck };