name: Deploy
on:
  push:
    branches:
      - feature/aws-deployment
env:
  BUCKET_NAME: "uniconnected2-frontend"
  AWS_REGION: "ap-southeast-2"
  CLOUDFRONT_DISTRIBUTION_ID: "E28VALZG6TPXIO"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
        id-token: write # This is required for requesting the JWT
        contents: read  # This is required for actions/checkout
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run Lint
        run: npm run lint
      - name: Build
        run: npm run build
        env:
          CI: false
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::116981780546:role/uniconnected-frontend-github-role
          role-session-name: frontendrolesession
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy to S3
        run: aws s3 sync ./out/. s3://${{ env.BUCKET_NAME }}